# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(235, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelModoCaptura = QtWidgets.QLabel(self.centralwidget)
        self.labelModoCaptura.setGeometry(QtCore.QRect(10, 10, 221, 18))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelModoCaptura.setFont(font)
        self.labelModoCaptura.setObjectName("labelModoCaptura")
        self.labelArea = QtWidgets.QLabel(self.centralwidget)
        self.labelArea.setGeometry(QtCore.QRect(10, 40, 59, 18))
        self.labelArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelArea.setObjectName("labelArea")
        self.labelDemora = QtWidgets.QLabel(self.centralwidget)
        self.labelDemora.setGeometry(QtCore.QRect(10, 80, 59, 18))
        self.labelDemora.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDemora.setObjectName("labelDemora")
        self.labelSegundos = QtWidgets.QLabel(self.centralwidget)
        self.labelSegundos.setGeometry(QtCore.QRect(140, 80, 59, 18))
        self.labelSegundos.setObjectName("labelSegundos")
        self.labelRutaGuardado = QtWidgets.QLabel(self.centralwidget)
        self.labelRutaGuardado.setGeometry(QtCore.QRect(10, 150, 221, 18))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.labelRutaGuardado.setFont(font)
        self.labelRutaGuardado.setObjectName("labelRutaGuardado")
        self.comboBoxArea = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxArea.setGeometry(QtCore.QRect(70, 30, 161, 28))
        self.comboBoxArea.setBaseSize(QtCore.QSize(0, 0))
        self.comboBoxArea.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBoxArea.setObjectName("comboBoxArea")
        self.comboBoxArea.addItem("")
        self.comboBoxArea.addItem("")
        self.checkBoxCopiarAlPortapapeles = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCopiarAlPortapapeles.setGeometry(QtCore.QRect(10, 110, 221, 22))
        self.checkBoxCopiarAlPortapapeles.setObjectName("checkBoxCopiarAlPortapapeles")
        self.lineEditRutaGuardado = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRutaGuardado.setGeometry(QtCore.QRect(10, 170, 181, 28))
        self.lineEditRutaGuardado.setObjectName("lineEditRutaGuardado")
        self.toolButtonDirDialog = QtWidgets.QToolButton(self.centralwidget)
        self.toolButtonDirDialog.setGeometry(QtCore.QRect(200, 170, 31, 28))
        self.toolButtonDirDialog.setObjectName("toolButtonDirDialog")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 200, 221, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButtonCaptura = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCaptura.setGeometry(QtCore.QRect(10, 220, 221, 41))
        icon = QtGui.QIcon.fromTheme("image-x-generic")
        self.pushButtonCaptura.setIcon(icon)
        self.pushButtonCaptura.setObjectName("pushButtonCaptura")
        self.pushButtonPreferencias = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPreferencias.setGeometry(QtCore.QRect(10, 270, 105, 41))
        icon = QtGui.QIcon.fromTheme("preferences-system")
        self.pushButtonPreferencias.setIcon(icon)
        self.pushButtonPreferencias.setObjectName("pushButtonPreferencias")
        self.pushButtonSalir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSalir.setGeometry(QtCore.QRect(125, 270, 105, 41))
        icon = QtGui.QIcon.fromTheme("window-close")
        self.pushButtonSalir.setIcon(icon)
        self.pushButtonSalir.setObjectName("pushButtonSalir")
        self.spinBoxSegundos = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxSegundos.setGeometry(QtCore.QRect(70, 70, 61, 30))
        self.spinBoxSegundos.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBoxSegundos.setDecimals(1)
        self.spinBoxSegundos.setObjectName("spinBoxSegundos")
        MainWindow.setCentralWidget(self.centralwidget)
        self.labelArea.setBuddy(self.comboBoxArea)
        self.labelDemora.setBuddy(self.spinBoxSegundos)
        self.labelRutaGuardado.setBuddy(self.lineEditRutaGuardado)

        self.retranslateUi(MainWindow)
        self.pushButtonSalir.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBoxArea, self.spinBoxSegundos)
        MainWindow.setTabOrder(self.spinBoxSegundos, self.checkBoxCopiarAlPortapapeles)
        MainWindow.setTabOrder(self.checkBoxCopiarAlPortapapeles, self.lineEditRutaGuardado)
        MainWindow.setTabOrder(self.lineEditRutaGuardado, self.toolButtonDirDialog)
        MainWindow.setTabOrder(self.toolButtonDirDialog, self.pushButtonCaptura)
        MainWindow.setTabOrder(self.pushButtonCaptura, self.pushButtonPreferencias)
        MainWindow.setTabOrder(self.pushButtonPreferencias, self.pushButtonSalir)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flameshot"))
        self.labelModoCaptura.setText(_translate("MainWindow", "Modo de captura:"))
        self.labelArea.setText(_translate("MainWindow", "&Área:"))
        self.labelDemora.setText(_translate("MainWindow", "&Demora:"))
        self.labelSegundos.setText(_translate("MainWindow", "segundos"))
        self.labelRutaGuardado.setText(_translate("MainWindow", "Ruta &guardado:"))
        self.comboBoxArea.setItemText(0, _translate("MainWindow", "  Pantalla completa"))
        self.comboBoxArea.setItemText(1, _translate("MainWindow", "  Sección rectangular"))
        self.checkBoxCopiarAlPortapapeles.setText(_translate("MainWindow", "Copiar captura al portapapeles"))
        self.toolButtonDirDialog.setText(_translate("MainWindow", "..."))
        self.pushButtonCaptura.setText(_translate("MainWindow", "Realizar captura"))
        self.pushButtonPreferencias.setText(_translate("MainWindow", "Preferencias"))
        self.pushButtonSalir.setText(_translate("MainWindow", "Salir"))

